# 指定语言环境
language: node_js

# 指定需要sudo权限
sudo: required

# 指定node_js版本
node_js: stable

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

notifications:
  # 钉钉机器人消息推送部署结果
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=${DINGDING__TOKEN}
    on_success: change 
    on_failure: always 

# 指定博客源码分支，因人而异。如果hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

# Start: Build Lifecycle
before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp
  - chmod +x _travis.sh

install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean && hexo g
  - gulp

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - ./_travis.sh
# End: Build LifeCycle
env:
 global:
   - GH_REF: github.com/immno/immno.github.io.git